project_name: install-slu

before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
builds:
  -
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/sikalabs/install-slu/version/version.Version=v{{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"
      - goos: linux
        goarch: arm
        goarm: 6
    binary: install-slu

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  -
    name: install-slu
    conflicts:
      - install-slu-edge
    tap:
      owner: sikalabs
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/sikalabs/install-slu
    url_template: "https://github.com/sikalabs/install-slu/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    caveats: "How to use this binary: https://github.com/sikalabs/install-slu"
    description: "install-slu"
    install: |
      bin.install "install-slu"
    test: |
      system "#{bin}/install-slu version"
  -
    name: install-slu-edge
    conflicts:
      - install-slu
    tap:
      owner: sikalabs
      name: homebrew-tap
    skip_upload: false
    homepage: https://github.com/sikalabs/install-slu
    url_template: "https://github.com/sikalabs/install-slu/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    caveats: "How to use this binary: https://github.com/sikalabs/install-slu"
    description: "install-slu"
    install: |
      bin.install "install-slu"
    test: |
      system "#{bin}/install-slu version"

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "sikalabs/install-slu:{{ .Tag }}"
      dockerfile: Dockerfile
      ids:
        - install-slu
      build_flag_templates:
        - "--platform=linux/amd64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabs/install-slu"
        - "--label=maintainer=SikaLabs Opensource &lt;opensource@sikalabs.com&gt;"
    - goos: linux
      goarch: arm64
      image_templates:
        - "sikalabs/install-slu:{{ .Tag }}-arm64v8"
      dockerfile: Dockerfile.arm64v8
      ids:
        - install-slu
      build_flag_templates:
        - "--platform=linux/arm64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabs/install-slu"
        - "--label=maintainer=SikaLabs Opensource &lt;opensource@sikalabs.com&gt;"
